### ISSUE TITLE
Update server networkId parameter logic

### ISSUE THREAD

**Issue by kostromich** [lunochkin/dex#70]
According to the specification
https://github.com/0xProject/standard-relayer-api/blob/master/ws/v2.md
`networkId` is an optional subscription parameter.

But if it's not sent by client then default value is 1 (aka mainnet).
It means that we have to enforce clients to send it if they want to interact with other network like kovan.

So, we will have such logic on server:
1. If client doesn't send `networkId` then default value is `1`
2. If result value is not equal to server `NETWORK_ID` then we throw an error, as now

The second part is to send `networkId` from clients in subscriptions to WS server.

- [ ] Change server so that it takes into account new default value logic according to the spec
- [ ] Change client so that it sends `networkId` in subscriptions

**Comment by lunochkin** [comment]
http://sra-spec.s3-website-us-east-1.amazonaws.com/#section/Network-Id
