### ISSUE TITLE
Subscribe frontend to history events with account as a parameter

### ISSUE THREAD

**Issue by lunochkin** [lunochkin/dex#90]
When issue https://github.com/lunochkin/dex/issues/89 is done we need to connect frontend with history events.
Subscription should take into account parameter `account`

- [ ] Send history events from server to client taking into account subscription params
- [ ] Update UI accordingly history events
- [x] Remove history loading in `refreshOrder` method of `V1OwnController`

**Comment by kostromich** [comment]
History update was removed in #94
